spring.application.name=otp-service

server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/otp_db
spring.datasource.username=postgres
spring.datasource.password=Swathi@98

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# OTP
otp.expiration.minutes=5
otp.max-attempts=3
otp.resend-seconds=60

# Twilio Credentials
twilio.account-sid=***********************************
twilio.auth-token=********************************
twilio.phone-number=+91**********
